### ISSUE TITLE
[Failure] Could not find file

### ISSUE THREAD

**Issue by mrzev123** [AIPALLC/DOSVision#3]
[Failure] Could not find file 'C:\Users\M\Desktop\DOSVision\TCPHeader.cs'.
[Failure] Could not find file 'C:\Users\M\Desktop\DOSVision\Program.cs'.
[Failure] Could not find file 'C:\Users\M\Desktop\DOSVision\UDPHeader.cs'.
[Failure] Could not find file 'C:\Users\M\Desktop\DOSVision\Utils\Other\Monitor.cs'.
[Failure] Could not find file 'C:\Users\M\Desktop\DOSVision\Properties\Settings.Designer.cs'.
[Failure] Could not find file 'C:\Users\M\Desktop\DOSVision\Properties\AssemblyInfo.cs'.
[Failure] Could not find file 'C:\Users\M\Desktop\DOSVision\Properties\Resources.Designer.cs'.

**Comment by Pronner** [comment]
What exactly is the issue?
I do not want to see the error, I need to see screenshots and an explanation of what you were trying to do.

**Comment by Pronner** [comment]
This issue will be closed if you do not reply by 24 hours.

**Comment by mrzev123** [comment]
![image](https://user-images.githubusercontent.com/39166589/159246733-c589050d-2764-43d3-a87c-8ad271f081a8.png)
Could not find file, missing files

**Comment by Pronner** [comment]
Try re-installing DOSVision?
I've never seen this problem before so I'm not sure how to fix it...
Also, I recommend using a release since the source code is outdated and is the first version of DOSVision.

**Comment by mrzev123** [comment]
Please can you give me a link those files missing.

**Comment by Pronner** [comment]
I’ll send a link in a few hours or so, a bit busy right now.

**Comment by mrzev123** [comment]
> I’ll send a link in a few hours or so, a bit busy right now.

thank you, ill be waiting

**Comment by mrzev123** [comment]
> https://www.mediafire.com/file/w03bnve33svqquy/DOSVision.zip/file
> 
> Here you go. Go nuts!

Wow it has an attack panel but there's no proxy/proxies. You should add proxies/proxy and threads to become powerful tool.

**Comment by Pronner** [comment]
Proxies might be added soon.

**Comment by Pronner** [comment]
> > https://www.mediafire.com/file/w03bnve33svqquy/DOSVision.zip/file
> > Here you go. Go nuts!
> 
> Wow it has an attack panel but there's no proxy/proxies. You should add proxies/proxy and threads to become powerful tool.

I've added a proxy in the new version, enjoy.

**Comment by mrzev123** [comment]
> I've added a proxy in the new version, enjoy.

I already checked no proxy, still the same. This is not worth to use only single IP. Need proxies http/socks4/socks5
![image](https://user-images.githubusercontent.com/39166589/161767242-efd35756-0cb4-471b-9d85-a21c9c9fbf42.png)

**Comment by Pronner** [comment]
I meant proxy on the anti-ddos. Now, it doesn't only block packets, it also blacklists the IP attacking you on your firewall. However, it only blocks the IP once there are severe connections.

**Comment by Pronner** [comment]
> > I meant proxy on the anti-ddos. Now, it doesn't only block packets, it also blacklists the IP attacking you on your firewall. However, it only blacklists the IP once there are severe connections. Therefore, it helps block connections or packets coming from that IP Address. Also, you just revealed your IP, I recommend deleting that.
> 
> I suggest not to use blocking to Firewall it will make the Server to lag and the Firewall will become not responding when it comes massive proxies because of too many ips added on the firewall.

True, I will be adding settings for limitations and more customization with how you want DOSVision to work instead of removing it though. Best of both worlds.

**Comment by mrzev123** [comment]
> > > I meant proxy on the anti-ddos. Now, it doesn't only block packets, it also blacklists the IP attacking you on your firewall. However, it only blacklists the IP once there are severe connections. Therefore, it helps block connections or packets coming from that IP Address. Also, you just revealed your IP, I recommend deleting that.
> > 
> > 
> > I suggest not to use blocking to Firewall it will make the Server to lag and the Firewall will become not responding when it comes massive proxies because of too many ips added on the firewall.
> 
> True, I will be adding settings for limitations and more customization with how you want DOSVision to work instead of removing it though. Best of both worlds.

I suggest to add blacklist.txt and execute block to firewall that is the best solution. So those legitimate ip (not proxy ip) that has been added to the blacklist.txt we can still remove it.

**Comment by Pronner** [comment]
I'll look into it and see what I can do.

**Comment by mrzev123** [comment]
> I was planning on adding a whitelist file where IPs are whitelisted by the user since I've found a bug on DOSVision that may block your own IP out when using a virtual private server cloud.

Yeah whitelist (optional) and blacklist, you should do that.

**Comment by mrzev123** [comment]
Anyway can you add proxies on the Attack Panel (http/socks4-5). Thank you.
