### ISSUE TITLE
Fixed this Issue as shown Picture

### ISSUE THREAD

**Issue by mrzev123** [AIPALLC/DOSVision#4]
I think it can't handle a true DDoS Attack, I tested on my end dedicated server.
![image](https://user-images.githubusercontent.com/39166589/159250104-13ebbb55-74d9-4379-8b0b-d4cf4e5e8886.png)

**Comment by Pronner** [comment]
I’ve never seen that error before, I’ll be looking into it but make sure you use the newest version, if you haven’t then try it out and see if it works. Either way, I’ll look into this issue and make sure everything is fine in the next version. Also, yes, DOSVision cannot handle huge attacks so I’ll be upgrading the blocker and it should be better in the next version.

**Comment by Pronner** [comment]
So I forgot about this issue and looking into it now I'm guessing there were too many connections or packets being sent from the attacker, therefore it wasn't able to keep going. However, that shouldn't be a problem in the new version.
